name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          pip install -e .

      # --- ADD THIS STEP ---
      - name: Verify installed packages
        run: pip list
      # ---------------------

      - name: Install Playwright Browsers and Dependencies
        run: python -m playwright install --with-deps # Keep this fix

      - name: Run Playwright tests
        run: pytest tests/ --trace --html=report.html --no-pdb

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: report.html
          retention-days: 7